apiVersion: v1
kind: Service
metadata:
  labels:
    app: front-end
  name: front-end
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: front-end
  type: ClusterIP
