apiVersion: v1
kind: Service
metadata:
  labels:
    app: product
    type: web
  name: product-web
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: product
    type: web
  type: ClusterIP