apiVersion: v1
kind: Secret
metadata:
  name: product
data:
  db_user: cm9vdA==
  db_password: cm9vdA==
  db_database: dGVzdC1wcm9kdWN0cy1kYg==
  db_host: aG9zdC5kb2NrZXIuaW50ZXJuYWw=
  db_port: NTQzMg==
