#!/bin/bash

eval $(minikube docker-env)

script_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

for app in "user" "product" "gateway" "front-end"; do
  echo "cding into: $script_directory/$app"
  cd "$script_directory/../$app"
  npm run docker-build
  kubectl create -f ./k8s
done

docker-compose up -d

echo 'waiting 30 seconds for postgresql to start...'
sleep 30

docker exec $(docker ps --format '{{.ID}}' -f name=trainingmicroservicesv3_db) \
  psql -d \
  test-products-db -c "CREATE DATABASE \"test-users-db\""

$script_directory/migrate
